services:
  web:
    image: docksal/apache:2.4-2.3
    volumes:
      - ${PROJECT_ROOT}:/var/www:rw
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
      - io.docksal.project-root=/var/www
    environment:
      - APACHE_DOCUMENTROOT=/var/www
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
